{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"internalError"},{"kind":"text","text":"("},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"IScribeAISDK"}],"title":"IScribeAI.ClientAuthenticationError.internalError(description:)","externalID":"s:12IScribeAISDK0A2AIC25ClientAuthenticationErrorO08internalF0yAESS_tcAEmF","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"description"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"symbolKind":"case"},"abstract":[{"type":"text","text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time."}],"references":{"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError":{"abstract":[{"type":"text","text":"An error that may occur while attempting to authenticate the provided JWT token."}],"kind":"symbol","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror","type":"topic","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ClientAuthenticationError","kind":"identifier"}],"navigatorTitle":[{"text":"ClientAuthenticationError","kind":"identifier"}],"title":"IScribeAI.ClientAuthenticationError","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK":{"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","role":"collection","type":"topic","kind":"symbol","title":"IScribeAISDK","url":"\/documentation\/iscribeaisdk","abstract":[{"text":"iScribe AI eliminates the burden of medical documentation, giving providers back time and energy to reinvest in their patients and their own wellbeing.","type":"text"},{"text":" ","type":"text"},{"text":"This iOS SDK provides direct access to the iScribe AI service. Simply record audio for a providerâ€™s session with a patient and submit. Our service will then auto-generate high quality medical documentation based on the content of that recording.","type":"text"}]},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI":{"abstract":[{"text":"This singleton is the primary interaction point for clients of the SDK. It handles starting and stopping recording as well as submitting recordings for processing and iScribe AI summary generation.","type":"text"}],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"IScribeAI"}],"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","url":"\/documentation\/iscribeaisdk\/iscribeai","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"IScribeAI","kind":"identifier"}],"title":"IScribeAI","type":"topic","role":"symbol"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError/internalError(description:)":{"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","abstract":[{"text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time.","type":"text"}],"role":"symbol","title":"IScribeAI.ClientAuthenticationError.internalError(description:)","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)","kind":"symbol"}}}