{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"modules":[{"name":"IScribeAISDK"}],"role":"symbol","title":"IScribeAI.ClientAuthenticationError.internalError(description:)","symbolKind":"case","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"internalError"},{"text":"(","kind":"text"},{"text":"description","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"externalID":"s:12IScribeAISDK0A2AIC25ClientAuthenticationErrorO08internalF0yAESS_tcAEmF"},"sections":[],"identifier":{"url":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)"]}],"abstract":[{"text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"internalError","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"description"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI":{"type":"topic","title":"IScribeAI","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"IScribeAI"}],"abstract":[{"text":"This singleton is the primary interaction point for clients of the SDK. It handles starting and stopping recording as well as submitting recordings for processing and iScribe AI summary generation.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"IScribeAI","kind":"identifier"}],"url":"\/documentation\/iscribeaisdk\/iscribeai"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK":{"kind":"symbol","type":"topic","abstract":[{"type":"text","text":"iScribe AI eliminates the burden of medical documentation, giving providers back time and energy to reinvest in their patients and their own wellbeing."},{"type":"text","text":" "},{"type":"text","text":"This iOS SDK provides direct access to the iScribe AI service. Simply record audio for a providerâ€™s session with a patient and submit. Our service will then auto-generate high quality medical documentation based on the content of that recording."}],"title":"IScribeAISDK","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK","url":"\/documentation\/iscribeaisdk","role":"collection"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError/internalError(description:)":{"title":"IScribeAI.ClientAuthenticationError.internalError(description:)","role":"symbol","identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError\/internalError(description:)","abstract":[{"type":"text","text":"An internal error occurred while attempting to validate the JWT token. This could be due to something like loss of network connection. The token authentication will be attempted again at a later time."}],"kind":"symbol","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror\/internalerror(description:)","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"internalError","kind":"identifier"},{"kind":"text","text":"("},{"text":"description","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":")","kind":"text"}],"type":"topic"},"doc://com.jpjventures.IScribeAISource/documentation/IScribeAISDK/IScribeAI/ClientAuthenticationError":{"abstract":[{"type":"text","text":"An error that may occur while attempting to authenticate the provided JWT token."}],"role":"symbol","title":"IScribeAI.ClientAuthenticationError","url":"\/documentation\/iscribeaisdk\/iscribeai\/clientauthenticationerror","kind":"symbol","type":"topic","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"ClientAuthenticationError","kind":"identifier"}],"identifier":"doc:\/\/com.jpjventures.IScribeAISource\/documentation\/IScribeAISDK\/IScribeAI\/ClientAuthenticationError","navigatorTitle":[{"text":"ClientAuthenticationError","kind":"identifier"}]}}}